const BOOKS = [
  { id: "GEN", name: "Genesis", chapters: 50 },
  { id: "EXO", name: "Exodus", chapters: 40 },
  { id: "LEV", name: "Leviticus", chapters: 27 },
  { id: "NUM", name: "Numbers", chapters: 36 },
  { id: "DEU", name: "Deuteronomy", chapters: 34 },
  { id: "JOS", name: "Joshua", chapters: 24 },
  { id: "JDG", name: "Judges", chapters: 21 },
  { id: "RUT", name: "Ruth", chapters: 4 },
  { id: "1SA", name: "1 Samuel", chapters: 31 },
  { id: "2SA", name: "2 Samuel", chapters: 24 },
  { id: "1KI", name: "1 Kings", chapters: 22 },
  { id: "2KI", name: "2 Kings", chapters: 25 },
  { id: "1CH", name: "1 Chronicles", chapters: 29 },
  { id: "2CH", name: "2 Chronicles", chapters: 36 },
  { id: "EZR", name: "Ezra", chapters: 10 },
  { id: "NEH", name: "Nehemiah", chapters: 13 },
  { id: "EST", name: "Esther", chapters: 10 },
  { id: "JOB", name: "Job", chapters: 42 },
  { id: "PSA", name: "Psalm", chapters: 150 },
  { id: "PRO", name: "Proverbs", chapters: 31 },
  { id: "ECC", name: "Ecclesiastes", chapters: 12 },
  { id: "SNG", name: "Song of Solomon", chapters: 8 },
  { id: "ISA", name: "Isaiah", chapters: 66 },
  { id: "JER", name: "Jeremiah", chapters: 52 },
  { id: "LAM", name: "Lamentations", chapters: 5 },
  { id: "EZK", name: "Ezekiel", chapters: 48 },
  { id: "DAN", name: "Daniel", chapters: 12 },
  { id: "HOS", name: "Hosea", chapters: 14 },
  { id: "JOL", name: "Joel", chapters: 3 },
  { id: "AMO", name: "Amos", chapters: 9 },
  { id: "OBA", name: "Obadiah", chapters: 1 },
  { id: "JON", name: "Jonah", chapters: 4 },
  { id: "MIC", name: "Micah", chapters: 7 },
  { id: "NAM", name: "Nahum", chapters: 3 },
  { id: "HAB", name: "Habakkuk", chapters: 3 },
  { id: "ZEP", name: "Zephaniah", chapters: 3 },
  { id: "HAG", name: "Haggai", chapters: 2 },
  { id: "ZEC", name: "Zechariah", chapters: 14 },
  { id: "MAL", name: "Malachi", chapters: 4 },
  { id: "MAT", name: "Matthew", chapters: 28 },
  { id: "MRK", name: "Mark", chapters: 16 },
  { id: "LUK", name: "Luke", chapters: 24 },
  { id: "JHN", name: "John", chapters: 21 },
  { id: "ACT", name: "Acts", chapters: 28 },
  { id: "ROM", name: "Romans", chapters: 16 },
  { id: "1CO", name: "1 Corinthians", chapters: 16 },
  { id: "2CO", name: "2 Corinthians", chapters: 13 },
  { id: "GAL", name: "Galatians", chapters: 6 },
  { id: "EPH", name: "Ephesians", chapters: 6 },
  { id: "PHP", name: "Philippians", chapters: 4 },
  { id: "COL", name: "Colossians", chapters: 4 },
  { id: "1TH", name: "1 Thessalonians", chapters: 5 },
  { id: "2TH", name: "2 Thessalonians", chapters: 3 },
  { id: "1TI", name: "1 Timothy", chapters: 6 },
  { id: "2TI", name: "2 Timothy", chapters: 4 },
  { id: "TIT", name: "Titus", chapters: 3 },
  { id: "PHM", name: "Philemon", chapters: 1 },
  { id: "HEB", name: "Hebrews", chapters: 13 },
  { id: "JAS", name: "James", chapters: 5 },
  { id: "1PE", name: "1 Peter", chapters: 5 },
  { id: "2PE", name: "2 Peter", chapters: 3 },
  { id: "1JN", name: "1 John", chapters: 5 },
  { id: "2JN", name: "2 John", chapters: 1 },
  { id: "3JN", name: "3 John", chapters: 1 },
  { id: "JUD", name: "Jude", chapters: 1 },
  { id: "REV", name: "Revelation", chapters: 22 },
];

const LOCAL_VERSIONS = [
  { id: "local-kjv", abbreviation: "KJV", name: "King James Version", language: "eng", languageName: "English", source: "local" },
  { id: "local-web", abbreviation: "WEB", name: "World English Bible", language: "eng", languageName: "English", source: "local" },
];

const LOCAL_BIBLE = {
  "local-kjv": {
    "JHN.15": {
      title: "The True Vine",
      copyright: "King James Version, public domain in the United States.",
      verses: [
        "I am the true vine, and my Father is the husbandman.",
        "Every branch in me that beareth not fruit he taketh away: and every branch that beareth fruit, he purgeth it, that it may bring forth more fruit.",
        "Now ye are clean through the word which I have spoken unto you.",
        "Abide in me, and I in you. As the branch cannot bear fruit of itself, except it abide in the vine; no more can ye, except ye abide in me.",
        "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing.",
        "If a man abide not in me, he is cast forth as a branch, and is withered.",
        "If ye abide in me, and my words abide in you, ye shall ask what ye will, and it shall be done unto you.",
        "Herein is my Father glorified, that ye bear much fruit; so shall ye be my disciples.",
      ],
    },
    "ROM.8": {
      title: "Life in the Spirit",
      copyright: "King James Version, public domain in the United States.",
      verses: [
        "There is therefore now no condemnation to them which are in Christ Jesus.",
        "For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death.",
        "For what the law could not do, in that it was weak through the flesh, God sending his own Son in the likeness of sinful flesh, and for sin, condemned sin in the flesh.",
        "That the righteousness of the law might be fulfilled in us, who walk not after the flesh, but after the Spirit.",
        "For they that are after the flesh do mind the things of the flesh; but they that are after the Spirit the things of the Spirit.",
      ],
    },
    "PSA.23": {
      title: "The Lord Is My Shepherd",
      copyright: "King James Version, public domain in the United States.",
      verses: [
        "The Lord is my shepherd; I shall not want.",
        "He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
        "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.",
        "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me.",
        "Thou preparest a table before me in the presence of mine enemies.",
        "Surely goodness and mercy shall follow me all the days of my life.",
      ],
    },
  },
  "local-web": {
    "JHN.15": {
      title: "The True Vine",
      copyright: "World English Bible, public domain.",
      verses: [
        "I am the true vine, and my Father is the farmer.",
        "Every branch in me that doesn't bear fruit, he takes away. Every branch that bears fruit, he prunes, that it may bear more fruit.",
        "You are already pruned clean because of the word which I have spoken to you.",
        "Remain in me, and I in you. As the branch can't bear fruit by itself unless it remains in the vine, so neither can you, unless you remain in me.",
        "I am the vine. You are the branches. He who remains in me and I in him bears much fruit, for apart from me you can do nothing.",
        "If a man doesn't remain in me, he is thrown out as a branch and is withered.",
        "If you remain in me, and my words remain in you, you will ask whatever you desire, and it will be done for you.",
        "In this my Father is glorified, that you bear much fruit; and so you will be my disciples.",
      ],
    },
    "ROM.8": {
      title: "Life in the Spirit",
      copyright: "World English Bible, public domain.",
      verses: [
        "There is therefore now no condemnation to those who are in Christ Jesus.",
        "For the law of the Spirit of life in Christ Jesus made me free from the law of sin and of death.",
        "For what the law couldn't do, in that it was weak through the flesh, God did, sending his own Son in the likeness of sinful flesh and for sin.",
        "That the ordinance of the law might be fulfilled in us, who walk not after the flesh, but after the Spirit.",
        "For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the Spirit, the things of the Spirit.",
      ],
    },
    "PSA.23": {
      title: "Yahweh Is My Shepherd",
      copyright: "World English Bible, public domain.",
      verses: [
        "Yahweh is my shepherd: I shall lack nothing.",
        "He makes me lie down in green pastures. He leads me beside still waters.",
        "He restores my soul. He guides me in the paths of righteousness for his name's sake.",
        "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me.",
        "You prepare a table before me in the presence of my enemies.",
        "Surely goodness and loving kindness shall follow me all the days of my life.",
      ],
    },
  },
};
